config:
  default: true
  MD013: false
  MD024:
    siblings_only: true
  MD033: false
  MD041: false
globs:
  - "**/*.md"
  - "**/*.mdx"
ignores:
  - "**/node_modules/**"
  - "**/.venv/**"
  - "**/target/**"
  - "**/out/**"
  - "packages/content-fixtures/invalid/**"
