cache = true
max_cache_age = "1d"
max_retries = 2
retry_wait_time = 1
accept = [200, 204, 206, 429]
exclude_path = ["packages/content-fixtures/invalid"]
exclude = ["^mailto:", "^http://127\\.0\\.0\\.1", "^http://localhost"]
